server.port=5555
spring.application.name=Ecommerce-API

jwt.secret=om_garmentbulandsharshop@#%$LKJS()#)#)#_03kla
jwt.expiration=3600000








spring.datasource.url=jdbc:mysql://localhost:3306/om_garment
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update